### ISSUE TITLE
hi,I can't running factomd.exe

### ISSUE THREAD

**Issue by PHPJourney** [FactomProject/factomd#28] opened 2016-10-05 07:43 UTC
This system is Window 2008 AND Window 10 

I'm try close factomd , then restart it. 

but give me some error.

Then I'm from factom-d.log file find the as following log

> 2016-10-05T15:18:57+08:00 [WARNING] FTMD: Go compiler version:go1.6.2
> 2016-10-05T15:18:58+08:00 [INFO] FTMD: Database started from: C:\Users\Administrator.PC-20140723ZFPN/.factom/ldb
> 2016-10-05T15:18:58+08:00 [INFO] WSAPI: Starting server
> 2016-10-05T15:18:58+08:00 [INFO] FTMD: Waiting for the processor to be initialized...
> 2016-10-05T15:19:00+08:00 [INFO] FTMD: Waiting for the processor to be initialized...
> 2016-10-05T15:19:02+08:00 [INFO] FTMD: Waiting for the processor to be initialized...
> 2016-10-05T15:19:03+08:00 [INFO] PROC: Loaded 57393 Directory blocks for chain: 000000000000000000000000000000000000000000000000000000000000000d

like initializezed afer, from block for chain 0 query . but BlockHeight is 57393

AND I can't find fctwallet.dat ,  Isn't backend my wallet

**Comment by MitchellBerry** [comment] 2016-10-05 21:21
Hello, possibly a duplicate of my issue: https://github.com/FactomProject/factomd/issues/23

In the comments Carryforward has a link to binaries compiled with Go1.7, this fixed everything for me on Win10.

Ctrl+F "dropjar" to find the downloads.

**Comment by carryforward** [comment] 2016-10-05 22:04
please let us know if either the 32 bit or 64 bit fixes from #23 fix the problem.

**Comment by PHPJourney** [comment] 2016-10-06 03:27
my system is 64bit.

**Comment by PHPJourney** [comment] 2016-10-06 03:38
oh, I wan't join my website. how i setting wallet.To ensure stable operation with once again safe start

**Comment by PHPJourney** [comment] 2016-10-06 04:04
@carryforward I can't find "dropjar" download address. it redirect HomePage.

**Comment by carryforward** [comment] 2016-10-07 00:36
sorry, I updated the original posts with new URLs

**Comment by PHPJourney** [comment] 2016-10-07 11:05
@carryforward OK,Think you.

**Comment by carryforward** [comment] 2016-10-20 02:45
did these work?

**Closed** 2016-10-20 02:45 UTC

**Comment by PHPJourney** [comment] 2016-10-20 03:44
yes,it's ok
