### ISSUE TITLE
`dblock-by-height` returns incorrect hash of ecblock (or ecblock at different height)

### ISSUE THREAD

**Issue by ilzheev** [FactomProject/factomd#995] opened 2020-05-03 18:09 UTC
1. Get DBlock **25437**
```
curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method": 
"dblock-by-height", "params":{"height":25437}}' \
-H 'content-type:text/plain;' https://api.factomd.net/v2
```

In response there is ECBlock **e44c378213ec13cb49a7a0cc53f4b735ab7bfbefb773bf0b6978dc2e8eef8d97**
```
{"chainid":"000000000000000000000000000000000000000000000000000000000000000c","keymr":"e44c378213ec13cb49a7a0cc53f4b735ab7bfbefb773bf0b6978dc2e8eef8d97"}
```

2. Check ECBlock e44c378213ec13cb49a7a0cc53f4b735ab7bfbefb773bf0b6978dc2e8eef8d97
```
curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method": 
"entrycredit-block", "params": {"keymr":"e44c378213ec13cb49a7a0cc53f4b735ab7bfbefb773bf0b6978dc2e8eef8d97"}}' \
-H 'content-type:text/plain;' https://api.factomd.net/v2
```

In response there is DBHeight **25429** instead of 25437:
```
{"jsonrpc":"2.0","id":0,"result":{"ecblock":{"header":{"bodyhash":"c26539a9b0e8473ad06bf01f9b4b144f32d4cb866ff8d5139bff40668e04e05d","prevheaderhash":"e23a3b63f889addde7d7d56ae979569ac573930fc022e4be8cb769926f008be6","prevfullhash":"24ab5d04fae6f7a24c3d879a65a362403469db7c946a8d6f8337c58752e5eb48","dbheight":25429
```

3. Check what's valid ECBlock for height 25437 and get different ECBlock
```
curl -X POST --data-binary '{"jsonrpc": "2.0", "id": 0, "method":
"ecblock-by-height", "params": {"height":25437}}' \
-H 'content-type:text/plain;' https://api.factomd.net/v2
```

Response:
```
{"ecblock":{"header":{"bodyhash":"b1f5544c607d51892f62d51b34889c73a4f0f1acd24ac55c8cd0c5d984ad34e0","prevheaderhash":"b5ddf0acb1f785c25d280e8d3084bea8f59196fb2c4a832c380ff523c5cdcb24","prevfullhash":"c8355e6d63bf5595bba1706d2138d2a8b8b379f729dbc72aed691f691fcc11ad"
```

**Comment by WhoSoup** [comment] 2020-05-04 12:21
I spent some time analyzing the data, and there are 24 missing EC Blocks: 
> 22880, 22883, 22940, 22949, 22976, 22978, 23267, 23268, 31459, 31460, 49235, 49236, 50157, 50158, 54353, 54354, 57214, 57215, 62781, 62782, 67811, 67812, 69086, 69087

For example, the DBlock entry for 22880 is: `5ae3ef7d02b9926a250e81cc2c548b9efb66c9fc454c6af59493e1555994c514` which does not exist in the database. The "DBHeight" of the EC chain is actually just the "sequence id", or a count of blocks, so for DBlock 22879, the EC block has a "height" of 22879 as expected. For 22881, the "height" is now 22880, since the block for DBlock 22880 is missing.

There are a total of 24 of these missing EC blocks and each time the "gap" between DBHeight and Sequence ID grows by one:

|from|to|diff|
|---|---|---|
|     0| 22879|0|
| 22881| 22882|-1|
| 22884| 22939|-2|
| 22941| 22948|-3|
| 22950| 22975|-4|
| 22977| 22977|-5|
| 22979| 23266|-6|
| 23269| 31458|-8|
| 31461| 49234|-10|
| 49237| 50156|-12|
| 50159| 54352|-14|
| 54355| 57213|-16|
| 57216| 62780|-18|
| 62783| 67810|-20|
| 67813| 69085|-22|
| 69088| 70410|-24|
| 70411| now|0|

In block 70,411 the error was corrected and the sequence was bumped up by 24 blocks. You can see this jump on the explorer for the ECBlock at height 70,411: https://explorer.factoid.org/data?type=ecblock&key=67ccc937bb46c821898ab0fae320af74b1b6865a2035b6bddc2c80b0771e653f Clicking "Previous Entry Credit Block" will take you the EC Block with a "height" of 70,386.

So to answer your initial question, at height **25,437** the difference between height and ecblock is 8 according to the table. That means the EC Block would have the sequence of "25,429" which it does.

**Comment by ilzheev** [comment] 2020-05-04 12:29
So, ecblock 25429 is valid for dblock 25437 (e.g. contains entry credit records for block 25437) and factomd returns correct ecblock hash in `dblock-by-height` API request?

And in Explorers we should show different EC blocks (!=dblock height) for dblocks in range 22881-70410?

**Comment by WhoSoup** [comment] 2020-05-04 12:38
> So, ecblock 25429 is valid for dblock 25437 (e.g. contains entry credit records for block 25437) and factomd returns correct ecblock hash in `dblock-by-height` API request?

Yeah, that's the valid EC Block and the dblock contains the correct hash. 

> And in Explorers we should show different EC blocks (!=dblock height) for dblocks in range 22881-70410?

Ideally we should display both "height" and "sequence" inside that range.

There's also the matter of the API itself. Right now if you call "get-ecblock-by-height" for heights between 70387 and 70410, you get a "block not found". We could hardcode the above table into the next API so that it works as expected when you supply the height (though there'd still be 24 missing blocks)

**Comment by ilzheev** [comment] 2020-05-04 12:43
What's about "duplicate" EC blocks at certain heights? (24 heights have 2 EC blocks with corresponding dbheight)

```
22880, 22882, 22938, 22946, 22972, 22973, 23261, 23262, 31451, 31452, 49225, 49226, 50145, 50146, 54339, 54340, 57198, 57199, 62763, 62764, 67791, 67792, 69064, 69065
```

E.g. height 22882

1st ec block 22882
```
[{"serverindexnumber": 0}, {"number": 1}, {"number": 2}, {"number": 3}, {"number": 4}, {"number": 5}, {"number": 6}, {"number": 7}, {"number": 8}, {"sig": "e49c31918d122065ef8604e4050f6bae15277ebd8221194ce209c9e4feb075e7c9a53a3b7a9c5083bfed2a79b9505295a81ed39baeb4cc74b2c4d9db01be8b0c", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "7bbdd5da67e70eae767a7b226dd10e4f7593f1b4d6436a139c26a6b588119d21", "millitime": 1454918893230}, {"sig": "ebbf2f7064164cfb92c649d990fafd1e6dbc26cbf5e00ac0dc50eb703d90d6ae46a4b727c2831e155ed57f5bf3f027bbd4335d77e46ae914d1436550b6d18601", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "cccdcb1ee7fe4d55642049916d61fa2faa45fa4c82e857f6dcf39fd3fcf79c15", "millitime": 1454918895479}, {"sig": "4a5b43a7bae0bbaac1baa78a3d9384853bc505e9baf70fe25119780063b019d5f2db3d8d05aada0af282f1e143fa9c2dd52f052e12c6c1de81ae48145ae02c05", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "7bbdd5da67e70eae767a7b226dd10e4f7593f1b4d6436a139c26a6b588119d21", "millitime": 1454918933060}, {"sig": "9d59607c061c29aa6e730e357735ee1e5a9590adb5b211542e4602bd4dc98ae3dc82d5c411ab2e6b44b414ad65cdb11f3ed5fda05687687b42f2e36bd3866e0e", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "cccdcb1ee7fe4d55642049916d61fa2faa45fa4c82e857f6dcf39fd3fcf79c15", "millitime": 1454918935321}, {"number": 9}, {"sig": "5fe4f20482aee04e9eaa8cf0ca3f63169def2d52df29df3e70336b8fed98289b30b345e5264c480103628ae8f84e691ce720dcd20a8b15326b80221b9c2b3901", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "0066368c79f7e23f58a7b0e1f6e634dbc68fabfeffcd769ca9f025505ca664bc", "millitime": 1454918973122}, {"sig": "4c857b0a0781b96020f1e1547389b59e959f3e204c2d25e492c9ef4586f099a69285c54de04a4e63b2e64a88295c3aff750016ff5e8a5b44eba3d4ad1b979100", "credits": 1, "version": 0, "ecpubkey": "17ef7a21d1a616d65e6b73f3c6a7ad5c49340a6c2592872020ec60767ff00d7d", "entryhash": "e8a18313b7d16856fe848ce76ead3a98b5f91f358c19ecdfd5f8c2f29f9bb18e", "millitime": 1454918982828}, {"number": 10}]
```

2nd ec block 228822
```
[{"sig": "8135fe4f91d69cdd0e87db41a9a90e6e92c63967f5cb94fba4b0042245791b8ed77c3069a9a9c0173eab0441c77933aa745f2bdd903ae5aa069d11c7205c5c02", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "7bbdd5da67e70eae767a7b226dd10e4f7593f1b4d6436a139c26a6b588119d21", "millitime": 1454919637560}, {"sig": "a0e3034b7544e920ecb516d77150a055e40ecd22d94eee69fc3d036473b366acea708f288a9681e0cf5ea93d2863877f6b446dc5ae9ae68c65dff269a7bfad0c", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "cccdcb1ee7fe4d55642049916d61fa2faa45fa4c82e857f6dcf39fd3fcf79c15", "millitime": 1454919639910}, {"sig": "374a3105b0b11d3248c67a3865615a1e239c2289d1a923246aade469aa2597b842b5211526ba0fd911af8b93f900422822b13597b1a4025fb9b6c923195c0d0e", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "a869449f83b5055ae9c4a946d8e60451d1c9d911e7c20f96ba05a25056b41aae", "millitime": 1454919647506}, {"sig": "4c7855e2a2f339505b1f1b0490671ef3150c35272cca7ed7d894e97e3fa39fef758681e3c2bb8eb638f785fa781141a9fe8469b23e3b6c103a826192f1ec350c", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "7bbdd5da67e70eae767a7b226dd10e4f7593f1b4d6436a139c26a6b588119d21", "millitime": 1454919697101}, {"sig": "e1651724af9f2abd3f7de1ad13d6cbab3671de0d488f1b150ade534a57d2cf2562a9171dec796a3832f28ff4c5d704a62cfef9635bfec1ffd642ab9f8a479702", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "cccdcb1ee7fe4d55642049916d61fa2faa45fa4c82e857f6dcf39fd3fcf79c15", "millitime": 1454919699402}, {"sig": "4b7eae356eca93e9f9f90abe960b3b2d7c118a6e7a7d6ac50f3fc6dc48629a2c9e153200e4b789c3e39f2cb12bf09bc56671b84f7ff35990376dca6da889480e", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "a869449f83b5055ae9c4a946d8e60451d1c9d911e7c20f96ba05a25056b41aae", "millitime": 1454919706760}, {"number": 2}, {"number": 3}, {"number": 4}, {"sig": "c9ea2f12c0f2d2e710d36720b09f89dc63681630d41ed0a62f2ea5ee1753891f7fff1c5cfc899d0ed8b9deaae3b68d0b698ab531e63c216820a16c926fa12e0e", "credits": 1, "version": 0, "ecpubkey": "3b6a27bcceb6a42d62a3a8d02a6f0d73653215771de243a63ac048a18b59da29", "entryhash": "522230838340d46c7bb736316838f9c68804e2367a340bcf025d8120e6dc67fe", "millitime": 1454919887514}, {"number": 5}, {"number": 6}, {"number": 7}, {"number": 8}, {"number": 9}, {"number": 10}]
```

Are both blocks are valid / do affect EC balances?

**Comment by WhoSoup** [comment] 2020-05-04 12:58
> What's about "duplicate" EC blocks at certain heights? (24 heights have 2 EC blocks with corresponding dbheight)

No, height 22882 only has one ecblock. The problem is if you call the API for "get-ecblock-by-height" for 22882, you get the ecblock with a **sequence** of 22882, which is actually the ecblock for height 22884.

To get the ECBlock for height 22881, you have to call "get-ecblock-by-height" with a "height" of 22880.

**Comment by WhoSoup** [comment] 2020-05-04 14:24
Seems like the API is consistent and will always return the "newest" ec block for each "height" query, or rather it will never return forked ec block.

|height|the keymr recorded in the directory block for that height|adjusted sequenceid|can be queried via "get-ecblock-by-height" & sequenceid|
|---|---|---|---|
|22880|5ae3ef7d02b9926a250e81cc2c548b9e fb66c9fc454c6af59493e1555994c514 |22880|false|
|22881|a9e8cdb39690a39a6faf2c980abc504e bf0b529ca944d2bc260f92875244976c |22880|true|
| | | | |
|22883|129d903f2d69acd1f0d55af9b1dc09dd cbc72ec6beb4d0796bc04474999cc8da |22882|false|
|22884|8fef0a804acebef5e68b3d35b1d3d56a 07a3e6b5ac744a7e81c53e6e174de1bb |22882|true|
| | | | |
|22940|215ae18a9062f2350b01746a27297790 fc724bbfb4cf38d8634fa25438361a4f |22938|false|
|22941|52da290265614ff219b2f1a4c6cc9b6b 8e14691c1dced991c0b76c1987266933 |22938|true|
| | | | |
|22949|a3feaf0f36ced6daf582eec584db1078 3246c7d20edf89580903685089423bf8 |22946|false|
|22950|b6e0c50ff19769484abaef1e65829829 da377db42349446274a50c48e8a01fcc |22946|true|
| | | | |
|22976|04069149cb53e6f4c2a0bd325623c3b1 df2e59c02ed6aae38e4f8c8bf0e6c951 |22972|false|
|22977|45146a4b32883031e1ffbfadc2568837 5a7d78964224a77e018c19224a8f9445 |22972|true|
| | | | |
|22978|1a2a3cc4d67904e7091d4ad505142df9 dfb4da4c243ea32d0e2e75a203a5b522 |22973|false|
|22979|bdaf1bc368e0d56563207266bcf4dbeb 96e522b739fcd7262567d9ef449679d2 |22973|true|
| | | | |
|23267|b65e150155cb9a08d326f91f97e3eefa dcffe54f5d225acd417074fe220a682a |23261|false|
|23268|4fb3b1e49551c625777a1d9649dca645 f1992eec81e68d3576f8ac4201346671 |23261|false|
|23269|95d91a8b5a7f798406f716afed8a9dda 07a15d1619cb308e654208d6207de466 |23261|true|
| | | | |
|31459|6471ea0b7c627cc2d84348a1d992a96d c44f123abd6f36f9cef7d1a27bebf8fa |31451|false|
|31460|abd3b6fe036dc5a0678a3757f2a59c72 3d036aed48f4b987b50ef6e9b396f56d |31451|false|
|31461|d5d59a11b01907fca10610f1ab909c1f 2d549bff129bc25c399a848d0046eaf9 |31451|true|
| | | | |
|49235|e1d55adf6201db6a47bb05bca4411d46 3c76c6657764aae176f9d2e0592b4aaf |49225|false|
|49236|45b6e650a77cdd2510db452427010bc4 beede8e9f8b01a38629aa7ef03e2fbac |49225|false|
|49237|9c51a7e5c7c7e1de3ce771d820074acc a91aa18c3a0fbfa99cdf2f7f8d388f9e |49225|true|
| | | | |
|50157|0207f74a9062be0ce5494ad69f3be8d9 94468a21fee70ca14621a1a778a6671c |50145|false|
|50158|9f0aa70298bad7e69b7aa1f4676c49f5 b4c915164e50aed0110cc0cdd18beeba |50145|false|
|50159|3c5446d27ae9698270a1f381f00a531c b8e96bce1d59cd47bb5657025a282a59 |50145|true|
| | | | |
|54353|59d3eff7717d874382004781171b2c89 95889bf9aecf67105523ea9b9628ca1d |54339|false|
|54354|8e8c59219df03332365c1edd82d91662 e1e43748f107ec7fb4fcd587e59cb4f8 |54339|false|
|54355|25c906b188198de6d113f232eeaf369f 1e100c89f566e98314de650284f5ad56 |54339|true|
| | | | |
|57214|d02f3375331d11273fc55f09e4f68f9a 108fc524948772e21788f2b53ae3fb60 |57198|false|
|57215|346e8fa769f951129f1f2b4c699b7aac 700f2b2a720a05a8cfb134838ac84408 |57198|false|
|57216|c7bae907e7effa2e5a7b940fc0c9eaae 1fa5638cc726a08effc32ba0c4d90251 |57198|true|
| | | | |
|62781|c3c1f52995b8cec450e7169fd5cfe124 d9d8222a9756badac60fdaaa51d0befb |62763|false|
|62782|c19f692923568bd639bfa71b14bb7f68 5d134353a99f29b48d4c751c36adffeb |62763|false|
|62783|a05c89282cc08e6f6f68c5a519cfa249 9ee4df55fdd717d32476978ecf7244e7 |62763|true|
| | | | |
|67811|c2b6a2ecfaaf6c6dea29ac2708f60bbb 13262a12010b2befde75fc23744b2160 |67791|false|
|67812|9499f831e3cb5a1311cb83d06223f758 b3fd2523201078a246fecb6081669c37 |67791|false|
|67813|76aecc8c5aa8f714ff284b928c9a0c38 b119748d2ec46f606c971efd04f0af5a |67791|true|
| | | | |
|69086|6088862f6d3e1daa165f5575d5621533 dbd4f6f1647311438e18a9286825e950 |69064|false|
|69087|927b491c94a67765b6849c380a1df86d 9f6b18801eaccbb4d56d60fd6f504737 |69064|false|
|69088|580efa3456a28e210e1b0b1412fb2c6a 749b8be2ae38ea49de2bc844167f8436 |69064|true|

**Comment by WhoSoup** [comment] 2020-05-04 14:45
The offshoots of the double-gaps are in fact chains of each other:
![image](https://user-images.githubusercontent.com/34172041/80978634-9d77d880-8e26-11ea-9f75-5cbc5b35a65f.png)

**Comment by PaulBernier** [comment] 2020-08-14 01:12
@ilzheev @WhoSoup is there any follow up action on this item? If not, let's close the issue.

**Closed** 2020-08-14 08:27 UTC
