### ISSUE TITLE
Invalid coinbase txs appear in pending-transactions API response with status TransactionACK (pokemon bug)

### ISSUE THREAD

**Issue by ilzheev** [FactomProject/factomd#1006] opened 2020-06-26 07:15 UTC
We already started investigating it with @WhoSoup 

The case:
1. My Factom Realtime Explorer is polling pending-transactions API with short time interval (seconds).
2. I noticed it catches coinbase invalid factoid txs from time to time (latest affected blocks 250675, 250925, 250950).
3. Invalid coinbase txs appear in pending-transactions API response with status "TransactionACK", but never appeared on the blockchain
4. Invalid coinbase txs appear in ANO payout blocks (% 25 == 0)

Block 250675:
txid 97e18c711c24dd7dc5be9d82722cfd6256575248106bcb4131cb8e11ff0b5534
outputs include payouts to ANOs

Block 250925:
txid 7b028d86dd832acafc041258db1a9a5a7047a82fa828a6670ecded1579e4a850
outputs null

Block 250950:
txid 23a56a843ad0dff7034b8e0c74434798a4a6d32c870ec86b0fa9fb74e2cca255
outputs null

**Comment by ilzheev** [comment] 2020-06-27 17:26
Hm, another one tx has been caught.
First seen: 27/06 08:49 UTC, equals to block **251126** (next block after ANO payout block).
Outputs null.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/4902353/85928257-a7fd9e00-b8bc-11ea-8f5c-fd095a5d0616.png">

**Comment by ilzheev** [comment] 2020-06-27 17:32
I accurately checked timestamps of previous affected txs.

Block 250675:
Timestamp 24/06 05:39 UTC, eq to block **250675**
txid 97e18c711c24dd7dc5be9d82722cfd6256575248106bcb4131cb8e11ff0b5534
**outputs include payouts to ANOs**

~~Block 250925:~~
Timestamp 25/06 23:29 UTC, eq to block **250926**
txid 7b028d86dd832acafc041258db1a9a5a7047a82fa828a6670ecded1579e4a850
**outputs null**

~~Block 250950:~~
Timestamp 26/06 03:39 UTC, eq to block **250951**
txid 23a56a843ad0dff7034b8e0c74434798a4a6d32c870ec86b0fa9fb74e2cca255
**outputs null**

**Comment by ilzheev** [comment] 2020-06-27 17:33
So, this invalid txs appear on ANO payout block (include ANO payouts in that case) **OR** the block after ANO payout block (and outputs are null).
@WhoSoup @carryforward

**Comment by ilzheev** [comment] 2020-06-28 09:43
And another one catch today.
Payout block, ANO payouts are into outputs.

<img width="1541" alt="image" src="https://user-images.githubusercontent.com/4902353/85944028-f8b8d980-b944-11ea-9479-12627f20fb00.png">

**Comment by WhoSoup** [comment] 2020-06-29 06:21
Does the fake transaction that shows up stay in there for the entire block or does it disappear before the block is over? In any case, I'm gonna see if I can replicate this behavior in a testable manner locally and/or find the cause.

**Comment by ilzheev** [comment] 2020-06-29 19:13
After running explorer locally and on production with full day, I concluded that wrong factoid txs appeared randomly — one follower returns it, while another one follower not. 

Moreover, the lifetime of such txs in pending-txs API response is less than 3s (polling interval I use). 

The time on server, that runs factomd that was being tested today, is good with no latency.

**Comment by ilzheev** [comment] 2020-06-30 16:31
@WhoSoup and me identified the issue.
A follower node (not specific one node, but in general) generates the default coinbase tx when the block is initiated, then being overridden by the real tx later. The polling manages to grab it between that.

In my local environment I was aggressively polling pending-txs API from the powerful machine (32GB+ RAM) – ~4-5 req per second. I managed to grab both fake factoid txs from 2 blocks in row (251600 & 251601) as you can see on screenshot below (fake txs has deleted_at IS NULL).

So it's not a pokemon bug, but fake txs generated by follower nodes appear in pending-txs API response, while they really should not.

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/4902353/86151306-9fe96c80-bb0f-11ea-8e39-bb79198ec3f6.png">

**Comment by WhoSoup** [comment] 2020-07-01 13:19
Here's a gist of what I think is happening. The data is pulled from a script that polls every 100ms and has expanded data (I added the timestamp and dbheight results).

https://gist.github.com/WhoSoup/4df6fcbd9139a692c717fbe6e89e770b

**Comment by WhoSoup** [comment] 2020-07-02 09:21
Okay, finally managed to track down the code that's responsible for this.

1. The new factoid block is created during minute 10 **before the dbsigs are present**, which means the code creates a new factoid block with the **timestamp of the previous block's creation**
2. Once the dbsig for VM0 is being **processed**, the code just shivs in the updated time 

This accounts for the ~100-300 milliseconds window that the new coinbase tx has the wrong txid. It happens every single block and I assume Anton's system didn't catch those because for 23 blocks, that transaction hash exists in the database. Not so for %25/25+1, where the combination of payouts + previous timestamp != empty + previous timestamp (or vice versa for the following block), so it looks like a completely new transaction.

The code for 2. is really buried deep inside unrelated core code and is a hallmark of why debugging factomd can be so challenging:
https://github.com/FactomProject/factomd/blob/0ff77090ab055d4c069612ca1a6814bde88155ab/state/stateConsensus.go#L2380-L2399

For the fix, I'm going to go with a non-invasive solution that only affects the behavior of GetPendingTransactions(). In the same code where it updates the coinbase timestamp, I'll just add a flag that the coinbase is "ready". If it's not ready, it won't show up in GetPendingTransactions().

**Comment by WhoSoup** [comment] 2020-10-13 06:25
This fix is included in the next release.

**Closed by WhoSoup** 2020-10-13 06:25 UTC
